In [3]:
import numpy as np 
import pandas as pd

In [5]:
data = pd.read_csv('D:\Machine Learning\K-Nearest Neibhors\Iris.csv')
data.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [6]:
data.shape

(150, 6)

In [7]:
data.value_counts('Species')

Species
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: count, dtype: int64

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB

In [9]:
data.describe()

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [10]:
x = data.iloc[:,1:5]
x

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0              5.1           3.5            1.4           0.2
1              4.9           3.0            1.4           0.2
2              4.7           3.2            1.3           0.2
3              4.6           3.1            1.5           0.2
4              5.0           3.6            1.4           0.2
..             ...           ...            ...           ...
145            6.7           3.0            5.2           2.3
146            6.3           2.5            5.0           1.9
147            6.5           3.0            5.2           2.0
148            6.2           3.4            5.4           2.3
149            5.9           3.0            5.1           1.8

[150 rows x 4 columns]

In [14]:
y = data.iloc[:,-1]
y

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: Species, Length: 150, dtype: object

In [15]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [16]:
x = scaler.fit_transform(x)
x[0:5]

array([[-0.90068117,  1.03205722, -1.3412724 , -1.31297673],
       [-1.14301691, -0.1249576 , -1.3412724 , -1.31297673],
       [-1.38535265,  0.33784833, -1.39813811, -1.31297673],
       [-1.50652052,  0.10644536, -1.2844067 , -1.31297673],
       [-1.02184904,  1.26346019, -1.3412724 , -1.31297673]])

In [17]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2)

In [18]:
x_train.shape

(120, 4)

In [20]:
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier(n_neighbors=1)
model.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=1)

In [21]:
pred = model.predict(x_test)
pred

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica',
       'Iris-virginica', 'Iris-setosa', 'Iris-versicolor',
       'Iris-virginica', 'Iris-virginica', 'Iris-setosa', 'Iris-setosa',
       'Iris-versicolor', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
       'Iris-setosa', 'Iris-virginica', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-virginica', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-virginica',
       'Iris-versicolor', 'Iris-setosa', 'Iris-setosa'], dtype=object)

In [22]:
y_test

44         Iris-setosa
62     Iris-versicolor
111     Iris-virginica
116     Iris-virginica
34         Iris-setosa
79     Iris-versicolor
83     Iris-versicolor
136     Iris-virginica
13         Iris-setosa
24         Iris-setosa
93     Iris-versicolor
30         Iris-setosa
16         Iris-setosa
76     Iris-versicolor
43         Iris-setosa
102     Iris-virginica
46         Iris-setosa
74     Iris-versicolor
134     Iris-virginica
148     Iris-virginica
82     Iris-versicolor
67     Iris-versicolor
20         Iris-setosa
89     Iris-versicolor
54     Iris-versicolor
86     Iris-versicolor
149     Iris-virginica
65     Iris-versicolor
38         Iris-setosa
41         Iris-setosa
Name: Species, dtype: object

In [25]:
from sklearn.metrics import accuracy_score, confusion_matrix
accuracy = accuracy_score(y_test, pred)
accuracy

0.9333333333333333

In [26]:
cm = confusion_matrix(y_test, pred)
cm

array([[11,  0,  0],
       [ 0, 11,  1],
       [ 0,  1,  6]])

In [27]:
result = pd.DataFrame(data = [y_test.values, pred], index=['y_test', 'pred'])

In [28]:
result

,0,1,2,3,4,5,6,7,8,9,...,20,21,22,23,24,25,26,27,28,29
y_test,Iris-setosa,Iris-versicolor,Iris-virginica,Iris-virginica,Iris-setosa,Iris-versicolor,Iris-versicolor,Iris-virginica,Iris-setosa,Iris-setosa,...,Iris-versicolor,Iris-versicolor,Iris-setosa,Iris-versicolor,Iris-versicolor,Iris-versicolor,Iris-virginica,Iris-versicolor,Iris-setosa,Iris-setosa
pred,Iris-setosa,Iris-versicolor,Iris-virginica,Iris-virginica,Iris-setosa,Iris-versicolor,Iris-virginica,Iris-virginica,Iris-setosa,Iris-setosa,...,Iris-versicolor,Iris-versicolor,Iris-setosa,Iris-versicolor,Iris-versicolor,Iris-versicolor,Iris-virginica,Iris-versicolor,Iris-setosa,Iris-setosa

In [30]:
correct_sum = []
for i in range (1,20):
    model = KNeighborsClassifier(n_neighbors=i)
    model.fit(x_train, y_train)
    pred = model.predict(x_test)
    correct = np.sum(pred == y_test)
    correct_sum.append(correct)

In [31]:
correct_sum

[np.int64(28),
 np.int64(28),
 np.int64(28),
 np.int64(27),
 np.int64(29),
 np.int64(29),
 np.int64(29),
 np.int64(28),
 np.int64(28),
 np.int64(29),
 np.int64(28),
 np.int64(28),
 np.int64(29),
 np.int64(29),
 np.int64(29),
 np.int64(29),
 np.int64(29),
 np.int64(29),
 np.int64(29)]

In [32]:
result = pd.DataFrame(data=correct_sum)
result.index = result.index+1
result.T

   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15  16  17  18  19
0  28  28  28  27  29  29  29  28  28  29  28  28  29  29  29  29  29  29  29

In [33]:
model = KNeighborsClassifier(n_neighbors=10)
model.fit(x_train, y_train)
pred = model.predict(x_test)

In [34]:
pred

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica',
       'Iris-virginica', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-virginica', 'Iris-setosa', 'Iris-setosa',
       'Iris-versicolor', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
       'Iris-setosa', 'Iris-virginica', 'Iris-setosa', 'Iris-versicolor',
       'Iris-virginica', 'Iris-virginica', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-setosa', 'Iris-setosa'], dtype=object)

In [35]:
accuracy = accuracy_score(y_test, pred)

In [36]:
accuracy

0.9666666666666667